<?php
/**
 *
 * @description Page loader
 *
 * @author Bina Commerce      <https://www.binacommerce.com>
 * @author C. M. de Picciotto <cmdepicciotto@binacommerce.com>
 *
 */
?>

<?php
/**
 *
 * @var \Magento\Framework\View\Element\Template $block
 *
 */
?>

<?php
/**
 *
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 *
 */
?>

<?php
/**
 *
 * @note Add loader element
 *
 */
?>
<div id="page_loader_container" class="page-loader-container">
    <span class="page-loader"></span>
</div>

<?php
/**
 *
 * @note Add loader logic as a vanilla JavaScript
 * @note The page loader needs to access document ready state to be able to know when to show and hide the loader. Since requirejs works by loading the code asynchronously, it is not possible to work with it to do the respective treatment since it is not possible to work with defined states asynchronously (for example, it may happen that when our asynchronous logic finishes loading, the expected states have already occurred)
 * @note It is created two states defined by the classes 'page-state-loading' and 'page-state-complete'. These classes are styled to show and hide the loader
 * @note It is added a little delay before hide the loader, just to ensure that the page is correctly loaded
 *
 * @link https://javascript.info/onload-ondomcontentloaded
 *
 */
?>
<?php
$scriptString = <<<script
    document.body.classList.add('page-state-loading');
    document.addEventListener('readystatechange', function () {
        if (document.readyState === 'complete') {
            setTimeout(() => {
                document.body.classList.add('page-state-complete');
            }, 1500);
        }
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
