<?php
/**
 *
 * @description Page loader
 *
 * @author Bina Commerce      <https://www.binacommerce.com>
 * @author C. M. de Picciotto <cmdepicciotto@binacommerce.com>
 *
 */
?>

<?php
/**
 *
 * @var \Magento\Framework\View\Element\Template $block
 *
 */
?>

<?php
/**
 *
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 *
 */
?>

<?php
/**
 *
 * @note Add loader element
 *
 */
?>
<div id="page_loader">
    <span class="page-loader"></span>
</div>

<?php
/**
 *
 * @note Add loader logic as a vanilla JavaScript
 * @note The page loader needs to access document ready state to be able to know when to show and hide the loader. Since requirejs works by loading the code asynchronously, it is not possible to work with it to do the respective treatment since it is not possible to work with defined states asynchronously (for example, it may happen that when our asynchronous logic finishes loading, the expected states have already occurred)
 *
 * @link https://javascript.info/onload-ondomcontentloaded
 *
 */
?>
<?php
$scriptString = <<<script
/**
 *
 * @note Get loader
 *
 */
var loader = document.getElementById('page_loader')

/**
 *
 * @note Show loader
 *
 */
_showLoader(loader);

/**
 *
 * @note Loading
 * @note It is created two states defined by the classes 'page-state-loading' (loading in progress) and 'page-state-complete' (loading complete)
 * @note It is added a little delay before hide the loader, just to ensure that the page is correctly loaded
 *
 */
document.body.classList.add('page-state-loading');
document.addEventListener('readystatechange', function () {
    if (document.readyState === 'complete') {
        setTimeout(() => {
            document.body.classList.add('page-state-complete');
            _hideLoader(loader);
        }, 4000);
    }
});

/**
 *
 * Show loader
 *
 * @param {HTMLDivElement} loader
 *
 * @returns {void}
 *
 * @private
 *
 */
function _showLoader(loader) {
    document.body.style.overflow = 'hidden';
    loader.style.visibility      = 'visible';
    loader.style.opacity         = 1;
    loader.style.zIndex          = 999999999999;
}

/**
 *
 * Hide loader
 *
 * @param {HTMLDivElement} loader
 *
 * @returns {void}
 *
 * @private
 *
 */
function _hideLoader(loader) {
    document.body.style.overflow = 'visible';
    loader.style.transition      = 'all 0.6s ease';
    loader.style.visibility      = 'hidden';
    loader.style.opacity         = 0;
    loader.style.zIndex          = 1;
}
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
